# Generated by Django 3.2 on 2025-02-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('ssn', models.CharField(max_length=11, unique=True)),
                ('work_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_status', models.CharField(max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account', models.BooleanField()),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(max_length=50)),
                ('agreed_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
